### ISSUE TITLE
Quality option

### ISSUE THREAD

**Issue by Mrunknow3** [siddharthsky/CustTermux-JioTVGo#11]
### Feature description

I start any channel that was so low quality add quality option

### Additional information

Nothing

**Comment by siddharthsky** [comment]
> ### Feature description
> 
> I start any channel that was so low quality add quality option
> ### Additional information
> 
> Nothing

In Web TV or IPTV player?

**Comment by Mrunknow3** [comment]
Web tv

**Comment by singhh9596** [comment]
I'm getting localhost error.

**Comment by siddharthsky** [comment]
> Web tv

Firstly, select 'High' for quality on the homepage, and then all channels will be played in the highest quality.

![Untitleds](https://github.com/user-attachments/assets/a670fdf4-b3b6-4759-a154-9928637447b0)
