### ISSUE TITLE
Not installing 

### ISSUE THREAD

**Issue by rishuverma75** [siddharthsky/CustTermux-JioTVGo#12]
![IMG_20240811_185837](https://github.com/user-attachments/assets/37f0cba5-f561-4bc2-897f-dcb6783217f3)

**Comment by siddharthsky** [comment]
Android 5 and 6 are not supported.

**Comment by siddharthsky** [comment]
Android 5 and 6 are not supported.

**Comment by rishuverma75** [comment]
ANY other option to run it
