### ISSUE TITLE
[Bug]: Port 5001 is already being used on my android tv.

### ISSUE THREAD

**Issue by Damnbuoy** [siddharthsky/CustTermux-JioTVGo#14]
### Problem description

Please add an option to change the port.

### What steps will reproduce the bug?

Just running it on a tv that is already listening to port 5001.

### System information

```shell
I cant copy from tv but:
Android version: 10
Device manufacturer: Oneplus
Device model: C00
```

**Comment by siddharthsky** [comment]
Use [CustTermux 4.0](https://bit.ly/CustTermux4), as the option to change the port has been added in the update.
