### ISSUE TITLE
Tata

### ISSUE THREAD

**Issue by Mrunknow3** [siddharthsky/CustTermux-JioTVGo#17]
### Feature description

Can you add tata servers bcz tata api is available and they have more channels. 

### Additional information

If you have any other india api like airtel Or dishtv you can add that too

**Comment by siddharthsky** [comment]
This is just a wrapper for the JioTV GO project to simplify server and IPTV setup. You can ask the developers on the [JioTV GO](https://github.com/rabilrbl/jiotv_go) GitHub page if they can assist with this.
