### ISSUE TITLE
[Bug]: Server status : Stopped on Fire TV 3rd GEN

### ISSUE THREAD

**Issue by devanshgupte** [siddharthsky/CustTermux-JioTVGo#25]
### Problem description

In initial installation, the server status is showing stopped and the screen is showing this.
17244258781756353401853781799692](https://github.com/user-attachments/assets/943e5901-7921-41e7-a2f0-4abc8b7b260f)

### What steps will reproduce the bug?

Initial installation 

### System information

```shell
*X11:

pkg install x11-repo

CustTERMUX JioTV_GO

CustTermux SiddharthSky

JioTVGo Rabilrbl

みらいかか

Script: version v6.9.1

Starting: Intent {act=com.termux.GetReceiver cmp=com.termux/.SkySharedPrefActivity (has extras)}

Captured value: Done

Initial setup is complete.

INSTALLATION PART 1

curl: (28) Failed to connect to bit.ly port 443 after 132428 ms: Couldn't connect to server Warning: Problem: timeout. Will
```

**Comment by siddharthsky** [comment]
> ### Problem description
> 
> In initial installation, the server status is showing stopped and the screen is showing this. 17244258781756353401853781799692](https://github.com/user-attachments/assets/943e5901-7921-41e7-a2f0-4abc8b7b260f)
> ### What steps will reproduce the bug?
> 
> Initial installation
> ### What is the expected behavior?
> 
> _No response_
> ### System information
> 
> ```shell
> *X11:
> 
> pkg install x11-repo
> 
> CustTERMUX JioTV_GO
> 
> CustTermux SiddharthSky
> 
> JioTVGo Rabilrbl
> 
> みらいかか
> 
> Script: version v6.9.1
> 
> Starting: Intent {act=com.termux.GetReceiver cmp=com.termux/.SkySharedPrefActivity (has extras)}
> 
> Captured value: Done
> 
> Initial setup is complete.
> 
> INSTALLATION PART 1
> 
> curl: (28) Failed to connect to bit.ly port 443 after 132428 ms: Couldn't connect to server Warning: Problem: timeout. Will
> ```


I have updated the script. Check now.
