### ISSUE TITLE
[Bug]: channels are not playing in firestick 4k

### ISSUE THREAD

**Issue by docjhatta** [siddharthsky/CustTermux-JioTVGo#26]
### Problem description

It gets installed peoperlly and got logged in too. But when you open a channel it says “an error occured while loading this video”. I dont know whats the problem. Can you please fix that. I am not in India as i am in canada. Just in case you require a location. Thank you. Hoping for a earlier fix please.
![image](https://github.com/user-attachments/assets/e14d77c3-b170-4886-aeb8-ff1af58d8550)

### What steps will reproduce the bug?

I dont know everything was done and logged in

### System information

```shell
Please ask me if you need any other information i would happy to provide that.
```

**Comment by siddharthsky** [comment]
Check if the JioTV official app works on your network. 

Note: JioTV officially only functions on Indian networks. You can try using a VPN.
