### ISSUE TITLE
[Bug]: Package installation stuck at "waiting for initial setup to complete"

### ISSUE THREAD

**Issue by abhishek7791** [siddharthsky/CustTermux-JioTVGo#30]
### Problem description

Package installation stuck at "waiting for initial setup to complete"

### What steps will reproduce the bug?

Package installation stuck at "waiting for initial setup to complete"

### System information

```shell
Package installation stuck at "waiting for initial setup to complete"
```

**Comment by siddharthsky** [comment]
> ### Problem description
> 
> Package installation stuck at "waiting for initial setup to complete"
> ### What steps will reproduce the bug?
> 
> Package installation stuck at "waiting for initial setup to complete"
> ### What is the expected behavior?
> 
> _No response_
> ### System information
> 
> ```shell
> Package installation stuck at "waiting for initial setup to complete"
> ```

Mention Android version/Fire TV OS version.

**Comment by abhishek7791** [comment]
Android 14. Nothing phone 1..

**Comment by abhishek7791** [comment]
![Screenshot_20240826-204456](https://github.com/user-attachments/assets/a03ce387-483d-48c8-ae3a-d5a300d826ef)

**Comment by siddharthsky** [comment]
> Android 14. Nothing phone 1..

Install Universal APK. - https://github.com/siddharthsky/CustTermux-JioTVGo/releases/download/x0.123.4/CustTermux_4.0_universal.apk 

And complete the initial setup steps.

**Comment by abhishek7791** [comment]
SAME ERROR ON UNIVERSAL APK..
![Screenshot_20240827-083000](https://github.com/user-attachments/assets/5bafafef-20bd-4513-887d-93a2171edcbf)

**Comment by siddharthsky** [comment]
Try the latest V4.2 to see if it fixes the issue.
https://github.com/siddharthsky/CustTermux-JioTVGo/releases/tag/x0.123.6

**Comment by abhishek7791** [comment]
Still same error in v4.2. In v4 and v4.2 google play protect popup unsafe to install app dialog box.
V3 was good, no play protect popup.

**Comment by siddharthsky** [comment]
> Still same error in v4.2. In v4 and v4.2 google play protect popup unsafe to install app dialog box. V3 was good, no play protect popup. V3 uses script version 6.4. and v4.2 uses 6.9.1. v3 is working good.

If v3 is working for you, could you please tell me which architectural APK you have installed?

**Comment by siddharthsky** [comment]
> ### Problem description
> 
> Package installation stuck at "waiting for initial setup to complete"
> ### What steps will reproduce the bug?
> 
> Package installation stuck at "waiting for initial setup to complete"
> ### What is the expected behavior?
> 
> _No response_
> ### System information
> 
> ```shell
> Package installation stuck at "waiting for initial setup to complete"
> ```

Toggling Developer options and USB debugging often solves the issue. Just make sure to reboot your device after toggling them.
