### ISSUE TITLE
[Bug] : OTP not coming

### ISSUE THREAD

**Issue by Shubham8050** [siddharthsky/CustTermux-JioTVGo#31]
### Problem description

Trying to send otp but otp is not getting received on mobile

### What steps will reproduce the bug?

After entering the mobile number in login popup

### What is the expected behavior?

OTP should be received in mobile

### System information

```shell
Fire tv stick
```

**Comment by crypto0007** [comment]
![IMG_20240826_204829](https://github.com/user-attachments/assets/abe87fed-9215-4806-a6d1-8b24328339a0)
Are you getting sort of this error?

**Comment by Shubham8050** [comment]
> ![IMG_20240826_204829](https://github.com/user-attachments/assets/abe87fed-9215-4806-a6d1-8b24328339a0)
> Are you getting sort of this error?
> Or
> Status shows stopped!!

Yes

**Comment by siddharthsky** [comment]
> ### Problem description
> 
> Trying to send otp but otp is not getting received on mobile
> ### What steps will reproduce the bug?
> 
> After entering the mobile number in login popup
> ### What is the expected behavior?
> 
> OTP should be received in mobile
> ### System information
> 
> ```shell
> Fire tv stick
> ```

Use compatible apk for firetv - [Download](https://github.com/siddharthsky/CustTermux-JioTVGo/releases/download/x0.123.4/CustTermux_4.0_android_5_universal_compatible_older_devices.apk)

The server should be running before log in.

**Comment by crypto0007** [comment]
> Tried again by downgrading the version, the otp is coming in the old version but not in the new version.

Which version did you tried?

**Comment by Shubham8050** [comment]
Closing this issue as it's fixed in the latest release 4.2
