### ISSUE TITLE
[Feature]: Multiple Selection for Language, and categories before m3u creation.

### ISSUE THREAD

**Issue by 888594** [siddharthsky/CustTermux-JioTVGo#37]
### Feature description

Requesting a feature that makes it easier to watch only channels that are needed as people don't watch all the languages and categories regularly. You can add this with initial setup & it should load it by default after that. 

### Additional information

previously add-ons did have this feature. it's hassel right now to search for channels from more than 1000 channels. 
![Screenshot 2024-08-29 165605](https://github.com/user-attachments/assets/bea966d5-f15d-4c95-9ade-46f8dd1ea8e1)
![Screenshot 2024-08-29 165628](https://github.com/user-attachments/assets/432a1a0d-32ab-4382-94bd-54df1da52275)

**Comment by siddharthsky** [comment]
This feature is already on the list for inclusion, and I will incorporate it into the upcoming v4.3 update.

**Comment by 888594** [comment]
Thank you 😊

**Comment by RamPrasath2812** [comment]
Expecting the same ..

**Comment by siddharthsky** [comment]
> ### Feature description
> 
> Requesting a feature that makes it easier to watch only channels that are needed as people don't watch all the languages and categories regularly. You can add this with initial setup & it should load it by default after that.
> ### Additional information
> 
> previously add-ons did have this feature. it's hassel right now to search for channels from more than 1000 channels. ![Screenshot 2024-08-29 165605](https://private-user-images.githubusercontent.com/123254950/362663841-bea966d5-f15d-4c95-9ade-46f8dd1ea8e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDUwMTIsIm5iZiI6MTcyNTQ0NDcxMiwicGF0aCI6Ii8xMjMyNTQ5NTAvMzYyNjYzODQxLWJlYTk2NmQ1LWYxNWQtNGM5NS05YWRlLTQ2ZjhkZDFlYThlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxMDExNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzUyYWFkNmNjNTI2NzM3NzkzZjI0OGIzOTk1N2FkOGRjNGVmZWNiNzk0ZTQ2ZGJkZTk1ODIyZjUwMGY3ZGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bsubuLWcrrbdr7DfhaEXwpWr0XpWqYgwFE7k9C2XlLg) ![Screenshot 2024-08-29 165628](https://private-user-images.githubusercontent.com/123254950/362663852-432a1a0d-32ab-4382-94bd-54df1da52275.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDUwMTIsIm5iZiI6MTcyNTQ0NDcxMiwicGF0aCI6Ii8xMjMyNTQ5NTAvMzYyNjYzODUyLTQzMmExYTBkLTMyYWItNDM4Mi05NGJkLTU0ZGYxZGE1MjI3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxMDExNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDQzMjQxNGU2NmU2ODkyZWI0MDRjODhlYmQwODA5YjZiMzg3MmUzYzYxMmNiYzBkMWU5ODJhY2I4MGU3Yjc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.56RKBVoWHEy02gb0VurPF9w6L8ZvtOMtoeAnVHiuVMc)

**While implementing this feature, I found that adding an option to customize the playlist would be quite a hassle.** However, this can be addressed by using a custom URL path without needing extra implementation. Additionally, in the case of WEB TV, custom selection across multiple categories and languages is not feasible as it is not implemented in the JioTV Go project itself.

For more details, refer to the documentation: [Customizing Playlist URL](https://jiotv_go.rabil.me/usage/paths.html#m3u-playlist-alias). You can use this guide to customize the default playlist URL and playlist.m3u
