### ISSUE TITLE
[Feature]: If possible add an option to copy 3rd party EPG url📋

### ISSUE THREAD

**Issue by TecnikOfficial** [siddharthsky/CustTermux-JioTVGo#38]
### Feature description

just like there is copy playlist url button📋 . there should be a third party epg list copy url option , as in tivimate default epg doesnt work but in ott navigator default one works . 

### Additional information

quick fix : i came across this [github repo](https://github.com/vsumavane/EPG_list) his epg list url: https://fomy.short.gy/epg.xml.gz or any other epg url thats active and it works fine on tivimate . this will be beneficial to people whose iptv player doesnt support default epg 
please look into this if possible ty

**Comment by 888594** [comment]
@siddharthsky it would be great if the generated epg gets saved on local storage so that we can directly implement it.

**Comment by siddharthsky** [comment]
> ### Feature description
> 
> just like there is copy playlist url button📋 . there should be a third party epg list copy url option , as in tivimate default epg doesnt work but in ott navigator default one works .
> ### Additional information
> 
> quick fix : i came across this [github repo](https://github.com/vsumavane/EPG_list) his epg list url: https://fomy.short.gy/epg.xml.gz or any other epg url thats active and it works fine on tivimate . this will be beneficial to people whose iptv player doesnt support default epg please look into this if possible ty

Thanks for the suggestion! However, this feature won't be added since you can already manually add custom EPG URLs in IPTV players like TiviMate.

**Comment by siddharthsky** [comment]
> ### Feature description
> 
> just like there is copy playlist url button📋 . there should be a third party epg list copy url option , as in tivimate default epg doesnt work but in ott navigator default one works .
> ### Additional information
> 
> quick fix : i came across this [github repo](https://github.com/vsumavane/EPG_list) his epg list url: https://fomy.short.gy/epg.xml.gz or any other epg url thats active and it works fine on tivimate . this will be beneficial to people whose iptv player doesnt support default epg please look into this if possible ty

Thanks for the suggestion! However, this feature won't be added since you can already manually add custom EPG URLs in IPTV players like TiviMate.

**Comment by siddharthsky** [comment]
> > > @siddharthsky it would be great if the generated epg gets saved on local storage so that we can directly implement it.
> > 
> > 
> > You can directly access the EPG file via `http://localhost:<port>/epg.xml.gz` You can either download the ZIP file from this link or use the URL directly in your IPTV player.
> 
> we'll have to download every few days and kodi does not read from localhost link. only ott navigator is the one that gets direct epg.

Try using this 
http://127.0. 0.1:<port>/epg.xml.gz

**Comment by 888594** [comment]
> > > > @siddharthsky it would be great if the generated epg gets saved on local storage so that we can directly implement it.
> > > 
> > > 
> > > You can directly access the EPG file via `http://localhost:<port>/epg.xml.gz` You can either download the ZIP file from this link or use the URL directly in your IPTV player.
> > 
> > we'll have to download every few days and kodi does not read from localhost link. only ott navigator is the one that gets direct epg.
> 
> Try using this 
> `http://127.0.0.1:<port>/epg.xml.gz`

Also doesn't work.
