### ISSUE TITLE
Bug: Server stopped after binary update

### ISSUE THREAD

**Issue by 888594** [siddharthsky/CustTermux-JioTVGo#39]
### Problem description

Whenever someone updates the binary. After update completion the server stops and never recover. Shows login service error. Happening on mibox4k.
![IMG_20240904_201500](https://github.com/user-attachments/assets/cbac3b8e-5790-47c0-81c2-4211ac56958b)

### What steps will reproduce the bug?

Go to extra and update 

### System information

```shell
Check uploaded picture.
```

**Comment by siddharthsky** [comment]
> ### Problem description
> Whenever someone updates the binary. After update completion the server stops and never recover. Shows login service error. Happening on mibox4k. ![IMG_20240904_201500](https://private-user-images.githubusercontent.com/123254950/364427409-cbac3b8e-5790-47c0-81c2-4211ac56958b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMDUyODAsIm5iZiI6MTcyNjIwNDk4MCwicGF0aCI6Ii8xMjMyNTQ5NTAvMzY0NDI3NDA5LWNiYWMzYjhlLTU3OTAtNDdjMC04MWMyLTQyMTFhYzU2OTU4Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QwNTIzMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmZhNWUyYzFmZTE4ODZiODExZTBlMTI5YmVhYWNlYjI3NzQ5YTIzYjY5ZGEzOTA5MmVkYzZjYTM2OTcwODM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mngS0nADUjoa_mCPqPbN9znSK0G5Gv4OE9kPzHU1amQ)
> 
> ### What steps will reproduce the bug?
> Go to extra and update
> 
> ### What is the expected behavior?
> _No response_
> 
> ### System information
> ```shell
> Check uploaded picture.
> ```

This issue has been fixed in CTx v4.3
