### ISSUE TITLE
[Feature]: Direct option to open web os as we click Jiotv app

### ISSUE THREAD

**Issue by Sandy4301** [siddharthsky/CustTermux-JioTVGo#40]
### Feature description

It is too complicated for my parents to open the jio tv app termux and then select web os from there. They click here and there and then lock themselves. It would be nice to add option to open directly web os as we open the jio tv app from the tv os.

### Additional information

No, I don't know any other applications with this feature.

**Comment by TecnikOfficial** [comment]
i understand ur issue ... u can do is go to ⚙️setup option in custermux app then select iptv player to open automatically and select iptv player as inbuilt from the list if u dont have 3rd party player installed . now when u open custermux app it will automatically open webtv section but the downside is once u go back and open custermux again it will not open default iptv player webtv automatically for tht u need 3rd party player like tivimate or ott navigator as for now default iptv web player only auto open once automatically after first time opening custermux app
