### ISSUE TITLE
[Bug]: bootstrap error while installing on fire tv stick 

### ISSUE THREAD

**Issue by Sunmayj** [siddharthsky/CustTermux-JioTVGo#41]
### Problem description

[Bug]: bootstrap error while installing on fire tv stick . I was able to install jio tv successfully on 1 fire tv stick but not able to install it on my 2nd fire tv stick. I get this error. I have tried resetting fire tv stick to factory reset but still same issue. Please assist 
![17258586779337888750591760849609](https://github.com/user-attachments/assets/79c88b11-8851-40a0-904b-a3e245025099)

### What steps will reproduce the bug?

Reinstall on fire tv stick 

### System information

```shell
Attached
```

**Comment by Sunmayj** [comment]
Error unable to install bootstrap 
Custtermux:jiotv go was unable to install the bootstrap packages. Try again or abort

**Comment by 888594** [comment]
disable developer option then try.

> Error unable to install bootstrap Custtermux:jiotv go was unable to install the bootstrap packages. Try again or abort

**Comment by Sunmayj** [comment]
Disabled developer option. It now shows installation blocked. For security reasons your tv is set to block installation of apps obtained from unknown source. Cancel or setting. When I click on settings it goes back to file explorer and nothing happens 
![Screenshot_2024-09-09-11-17-37-48_92460851df6f172a4592fca41cc2d2e6](https://github.com/user-attachments/assets/8789be26-a0d5-4357-b6c9-500a6ba42000)

**Comment by TecnikOfficial** [comment]
@Sunmayj can u sideload/install other apks normally ?

**Comment by TecnikOfficial** [comment]
i mean other apps like send to tv app does this installation block pop up comes when u try to install other apps @Sunmayj

**Comment by Sunmayj** [comment]
> i mean other apps like [send to tv](https://play.google.com/store/apps/details?id=com.yablio.sendfilestotv&hl=en_US) app .....does this installation block pop up comes when u try to install other apps @Sunmayj

@siddharthsky . Yes I was able to install send to tv, file explorer and other apps from Play Store with out any issue

**Comment by TecnikOfficial** [comment]
i meant not from playstore but from apk

**Comment by Sunmayj** [comment]
> i meant not from playstore but from apk .... for eg : [apkmirror](https://www.apkmirror.com/apk/yuliskov/stn-stable-android-tv/stn-stable-android-tv-23-30-release/smarttube-android-tv-23-30-2-android-apk-download/) find any app apk u want for tv to test and install.... coz i think u need to [enable unknown sources](https://robots.net/how-to-guide/how-to-allow-firestick-to-download-from-unknown-sources/) in android settings to install any apk properly

Hi @siddharthsky . It looks like I got it fixed. I am using 2nd fire tv stick which is old enough like from 2 to 3 years back. I tried using apk of android 5 version 72 mb file. That worked for me on this fire stick.
