### ISSUE TITLE
[Bug]: The application not launching channels (loading for longer time without any error)

### ISSUE THREAD

**Issue by akshaykmr330** [siddharthsky/CustTermux-JioTVGo#46]
### Problem description

After opening any channel it is opening for longer time and channel is not played. Tried with 3 to 4 channels same issue exists. 

Loads for longer time and channel is not played (Not getting any error)

### What steps will reproduce the bug?

1. Open Jio TV go App
2. Wait for status : Running / Login : Logged in
3. Open WEBTV 
4. Try to open any channels 

### What is the expected behavior?

Expected : 
The channel should be open / played without any issues

Actual : 
Loading for longer time and not open / play any channel (no error information)

### System information

```shell
＊X11: pkg install x11-repo
CustTERMUX • JioTV_GO
CustTermux • SiddharthSky
JioTVGo • Rabilrbl
.................................
Script: version v6.9.2 [7 series]
JioTV Go version 3.8.0
.................................
Starting: Intent { act=com. termux.GetReceiver cmp=com. termux/.SkySharedPrefActivity (has extras) )
Captured value: No
Running Server on port 5001
Newer version v3.9.3 available. Run ‘jiotv go update’ to update.
Starting iow Go server in background.••
JioTV Go server started successfully in background.
Starting: Intent ( act=com.termux.SKY_ACTION cmp=com. termux/.SkyActionActivity (has extras)
HOME
```

**Comment by 888594** [comment]
Update binary

**Comment by akshaykmr330** [comment]
> Update binary

May i know how to update binary ? 
Can you provide any steps ?

**Comment by hrishikesharma** [comment]
@akshaykmr330  
1. Click on EXTRA 
2. Choose the first option "Update JioTV Go"
3. Click OK

After updating JioTvGO I faced this issue https://github.com/siddharthsky/CustTermux-JioTVGo/issues/45

Please let me know if you also face similar issue

**Comment by Bharath261** [comment]
@hrishikesharma 

I tried to fix the problem by updating the binary i.e, I updated from v3.8.0 to v3.9.3, But the problem persists.

The above problem is not applicable to all the channels, Free to air channels are working properly the issue is with all the other channels.

**Comment by 888594** [comment]
Uninstall the existing app. Redownload apk and reinstall. I just had to do this on my phone to make it work.

**Comment by Bharath261** [comment]
It's working now without any problems.

**Comment by TecnikOfficial** [comment]
> @akshaykmr330
> 
> 1. Click on EXTRA
> 2. Choose the first option "Update JioTV Go"
> 3. Click OK
> 
> After updating JioTvGO I faced this issue #45
> 
> Please let me know if you also face similar issue

can we set to auto update binary

**Comment by siddharthsky** [comment]
> > @akshaykmr330
> > 
> > 1. Click on EXTRA
> > 2. Choose the first option "Update JioTV Go"
> > 3. Click OK
> > 
> > After updating JioTvGO I faced this issue #45
> > Please let me know if you also face similar issue
> 
> can we set to auto update binary

Currently, not possible

**Comment by 888594** [comment]
> > Uninstall the existing app. Redownload apk and reinstall. I just had to do this on my phone to make it work. Still not working in android 9.
> 
> To fix,
> 
> Extra > Reinstall

Tried everything from scratch. Throws login service error. Keeps checking service status.

**Comment by TecnikOfficial** [comment]
> Tried everything from scratch. Throws login service error. Keeps checking service status.

same here cant get it to work on external iptv player but can view few channels on inbuilt web player

**Comment by siddharthsky** [comment]
> > Tried everything from scratch. Throws login service error. Keeps checking service status.
> 
> same here cant get it to work on external iptv player but can view few channels on inbuilt web player

See if the latest release solved this issue.
