### ISSUE TITLE
[Bug]: ZEE TV channels missing from jiotv app

### ISSUE THREAD

**Issue by Sunmayj** [siddharthsky/CustTermux-JioTVGo#47]
### Problem description

Team after recent buffer issue and reinstall the apk we are missing all Zee TV channels from the list. Anyway we can get zee channels back ?

### What steps will reproduce the bug?

Extra.. reinstall 

### What is the expected behavior?

Zee channels were working till 9th sep but now not showing in Web TV list of channels 

### System information

```shell
Webtv list of channels
```

**Comment by TecnikOfficial** [comment]
ya missing here also cant play any channel on external iptv app now only can play few channel in inbuilt web player

**Comment by Nexus-Gits** [comment]
This is not the CustTermux Jio tv go app issue. Jio tv removed all the Zee and &pictures channels.
![Uploading Jio.png…]()

**Comment by TecnikOfficial** [comment]
now where we can watch those channel ? any help coz i installed jiotv only for those channels as sony live channels r gone too

**Comment by vstnexus** [comment]
> now where we can watch those channel ? any help coz i installed jiotv only for those channels as sony live channels r gone too

Same question! Did you find any solution?

**Comment by TecnikOfficial** [comment]
ya i switched to m3u url system coz they r more reliable u only need active links from telegram channels and put it in [ott navigator](https://play.google.com/store/apps/details?id=appnovatica.tv)

**Comment by vinayak104** [comment]
> @vstnexus ya i switched to m3u url system coz they r more reliable u only need to get active free links from telegram channels ( tht u need to find it yourself for your region ) and put it in [ott navigator](https://play.google.com/store/apps/details?id=appnovatica.tv) and watch u dont need other apps note: u need to get new links once old one expires

Which telegram channel provides more reliable m3u files?

**Comment by TecnikOfficial** [comment]
> Which telegram channel provides more reliable m3u files?
cant link telegram channels here but u can check out this [github repository](https://github.com/kananinirav/Indian-IPTV-App) use app or copy m3u url (check in credits channel source)  paste in ott navigator

**Comment by TecnikOfficial** [comment]
> Everyone please let me know here when Zee channels resume so i will reinstall the app.

i dont think zee will return .... with zee and sony gone ... only colors channel left and rest other channels works in default jiotv android tv app :(

**Comment by siddharthsky** [comment]
Jiotv_go is an unofficial method to watch the channels that are available on the jio tv app.

Jio removed zee and sony channels from the official app. So it is not available in the jiotv_go as well.

Look for other sources if you want to watch those.
