### ISSUE TITLE
[Feature]: CustTerm Minimizer without launching IPTV

### ISSUE THREAD

**Issue by d1g33k** [siddharthsky/CustTermux-JioTVGo#48]
### Feature description

One of the use cases is to launch JioTVGo on boot to keep it ready for IPTV but with other accessible content on various OTT apps, it is possible that the IPTV may not be used until later in the session.

Thus, having CustTerm minimize by itself after initialisation without launching the IPTV app is also a possible use case. Presently, the minimize option is only available after selecting the IPTV app to be launched and instead it should be a general option.

Also, since CustTerm takes more than a minute to launch after boot, it sometimes interrupts other apps that have been launched. If it is possible for it to not interrupt other apps at launch, then that would be great as well.

### Additional information

Existing minimize functionality limited to when launching the IPTV app that logically should be extendable. Also not sure if the display over other app option can be leveraged to allow control to go back to the app over which CustTerm launches.

**Comment by siddharthsky** [comment]
> ### Feature description
> 
> One of the use cases is to launch JioTVGo on boot to keep it ready for IPTV but with other accessible content on various OTT apps, it is possible that the IPTV may not be used until later in the session.
> 
> Thus, having CustTerm minimize by itself after initialisation without launching the IPTV app is also a possible use case. Presently, the minimize option is only available after selecting the IPTV app to be launched and instead it should be a general option.
> 
> Also, since CustTerm takes more than a minute to launch after boot, it sometimes interrupts other apps that have been launched. If it is possible for it to not interrupt other apps at launch, then that would be great as well.
> ### Additional information
> 
> Existing minimize functionality limited to when launching the IPTV app that logically should be extendable. Also not sure if the display over other app option can be leveraged to allow control to go back to the app over which CustTerm launches.

For that, I will be adding a background auto-start option that will instantly start the server in the background. This way, when the TV starts, the server will already be ready.

**Comment by siddharthsky** [comment]
Addressed in v4.4
