### ISSUE TITLE
[Bug]:  playback error in KODI

### ISSUE THREAD

**Issue by Ursgirishgupta** [siddharthsky/CustTermux-JioTVGo#5]
### Problem description

It's working great in OTT Nav, but when i try to host it to KODI getting playback failed error. 
![b1a54a25-1e36-425b-be13-91abd8a745a6](https://github.com/user-attachments/assets/ca06d145-d2af-4a62-80e4-38f6eaa762db)

### What steps will reproduce the bug?

Try hosting it to kodi you will face the error, i found the same error in both 20.5 and 21 version of kodi. 

### System information

```shell
Playing it in my Android TV in KODI.
```

**Comment by Ursgirishgupta** [comment]
@siddharthsky

**Comment by siddharthsky** [comment]
Use Kodi v19.0

**Comment by siddharthsky** [comment]
Use Kodi v19.0

**Comment by siddharthsky** [comment]
### Fix for KODI playback failed issue
In IPTV Simple Client, go to Expert Settings, and then under Advanced, change the user agent to 

```
Mozilla/5.0
```
![kodi fix](https://github.com/user-attachments/assets/faa39ef3-65b5-4d91-8cff-14a75bd5f205)
