### ISSUE TITLE
Request to Add Star Network Channels and App Navigation

### ISSUE THREAD

**Issue by Bharath2207** [siddharthsky/CustTermux-JioTVGo#50]
### Problem description

First of all, thank you for your great work. Please consider star network channels like Star Plus. If that's not possible, Jio TV Plus offers an option to navigate to apps like Hotstar and Zee5 to watch live TV. It would be great if you could implement a similar feature so that I can use it with my friend's subscription.

### What steps will reproduce the bug?

You can check channels list 

### System information

```shell
Our is not required for this
```

**Comment by siddharthsky** [comment]
> ### Problem description
> 
> First of all, thank you for your great work. Please consider star network channels like Star Plus. If that's not possible, Jio TV Plus offers an option to navigate to apps like Hotstar and Zee5 to watch live TV. It would be great if you could implement a similar feature so that I can use it with my friend's subscription.
> ### What steps will reproduce the bug?
> 
> You can check channels list
> ### What is the expected behavior?
> 
> _No response_
> ### System information
> 
> ```shell
> Our is not required for this
> ```
CustTermux is just a wrapper to run JioTV Go. You can raise an issue on the official [JioTV Go repository](https://github.com/rabilrbl/jiotv_go) if you want additional features.
