### ISSUE TITLE
Getting Error: failed to download binary

### ISSUE THREAD

**Issue by ansarshaikh-infosec** [siddharthsky/CustTermux-JioTVGo#52]
![20240914_114603](https://github.com/user-attachments/assets/7bd1ac8d-d90e-45da-8869-abaebcf8ba6e)

**Comment by siddharthsky** [comment]
> ![20240914_114603](https://private-user-images.githubusercontent.com/174892601/367493096-7bd1ac8d-d90e-45da-8869-abaebcf8ba6e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyOTUxMTAsIm5iZiI6MTcyNjI5NDgxMCwicGF0aCI6Ii8xNzQ4OTI2MDEvMzY3NDkzMDk2LTdiZDFhYzhkLWQ5MGUtNDVkYS04ODY5LWFiYWViY2Y4YmE2ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQwNjIwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTkzZjlhNmY4ZmI5NjZlNWU4ZmRhNmY3NjIwYmM0OTUzN2QzNWQ2YzBhNDhiN2Y5ZWRkNWM1ZTBiNjJiNGVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vlK_4uOtR41JnuD0_K8vaezfN3LUdXSRPFyUXub_pkc)

Network issue.

**Comment by ansarshaikh-infosec** [comment]
what's the issue? My internet connection is working fine. Is there a problem with the server? Please check and let me know. I've been trying since yesterday."

**Comment by ansarshaikh-infosec** [comment]
I'm not getting channels like Zee TV, what's the issue?

**Comment by siddharthsky** [comment]
> I'm not getting channels like Zee TV, what's the issue?

Jiotv_go is an unofficial method to watch the channels that are available on the jio tv app.

Jio removed zee and sony channels from the official app. So it is not available in the jiotv_go as well.

Look for other sources if you want to watch those.
