### ISSUE TITLE
[Bug]: Loading in loop after 10 mins

### ISSUE THREAD

**Issue by adarshsivan** [siddharthsky/CustTermux-JioTVGo#53]
### Problem description

Whenever we watch a channel continuously for more than 10 - 15 mins. The loading icon appears and not able to view the channel.

### What steps will reproduce the bug?

Watch any channel for more than 10 - 15 mins to reproduce the issue. I have faced the issue on channel named “Flowers TV”.

### What is the expected behavior?

Should be able to watch the channel without any interruptions.

### System information

```shell
NA
```

**Comment by siddharthsky** [comment]
> ### Problem description
> 
> Whenever we watch a channel continuously for more than 10 - 15 mins. The loading icon appears and not able to view the channel.
> ### What steps will reproduce the bug?
> 
> Watch any channel for more than 10 - 15 mins to reproduce the issue. I have faced the issue on channel named “Flowers TV”.
> ### What is the expected behavior?
> 
> Should be able to watch the channel without any interruptions.
> ### System information
> 
> ```shell
> NA
> ```

Without system information, logs, or a screenshot, I can't help with the issue.

**Comment by siddharthsky** [comment]
Closing due to lack of further information.
