### ISSUE TITLE
[Feature]: Auto Updater Issue

### ISSUE THREAD

**Issue by spacex97** [siddharthsky/CustTermux-JioTVGo#56]
### Feature description

Hello, I have seen issue with latest jiotv_go build and I recommend to remove auto updater instead there should be manual updater this way we can be at stable build. This is required immediately since new builds are throwing errors.

### Additional information

Welcome to CustTermux!

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * X11:      pkg install x11-repo
 ---------------------------
CustTERMUX - JioTV_GO
---------------------------
CustTermux - SiddharthSky
JioTVGo - Rabilrbl
---------------------------
###### 十人十色 ######
JioTV Go is up to date (version 3.9.5).
Script : version v6.9.2x [7 series]
JioTV Go version v3.9.5
---------------------------
Starting: Intent { act=com.termux.GetReceiver cmp=com.termux/.SkySharedPrefActiv                                                                                                         ity (has extras) }
Captured value: Yes
Running Server Locally on port 5001
INFO: No config file found, using environment variables
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/rabilrbl/jiotv_go/v3/pkg/store.Set({0x545b931, 0x8}, {0x268983b0, 0x1                                                                                                         0})
        github.com/rabilrbl/jiotv_go/v3/pkg/store/store.go:69 +0xb4
github.com/rabilrbl/jiotv_go/v3/pkg/utils.GenerateRandomString()
        github.com/rabilrbl/jiotv_go/v3/pkg/utils/utils.go:568 +0x160
github.com/rabilrbl/jiotv_go/v3/pkg/utils.GetDeviceID()
        github.com/rabilrbl/jiotv_go/v3/pkg/utils/utils.go:334 +0xb4
github.com/rabilrbl/jiotv_go/v3/internal/handlers.Init()
        github.com/rabilrbl/jiotv_go/v3/internal/handlers/handlers.go:52 +0x184
github.com/rabilrbl/jiotv_go/v3/cmd.JioTVServer({0x545d149, 0x9}, {0xfffce4f7, 0                                                                                                         x4}, {0x0, 0x0}, 0x0)
        github.com/rabilrbl/jiotv_go/v3/cmd/jiotv_go.go:95 +0x5b0
main.main.func1(0x264194c0)
        github.com/rabilrbl/jiotv_go/v3/main.go:47 +0x260
github.com/urfave/cli/v2.(*Command).Run(0x265320c8, 0x264194c0, {0x26502ff0, 0x3                                                                                                         , 0x3})
        github.com/urfave/cli/v2@v2.27.4/command.go:276 +0x7b4
github.com/urfave/cli/v2.(*Command).Run(0x26532b48, 0x26419400, {0x264180c0, 0x4                                                                                                         , 0x4})
        github.com/urfave/cli/v2@v2.27.4/command.go:269 +0xaac
github.com/urfave/cli/v2.(*App).RunContext(0x264039e8, {0x5d56800, 0x61377e8}, {                                                                                                         0x264180c0, 0x4, 0x4})
        github.com/urfave/cli/v2@v2.27.4/app.go:333 +0x62c
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.27.4/app.go:307
main.main()
        github.com/rabilrbl/jiotv_go/v3/main.go:231 +0x1a98

**Comment by siddharthsky** [comment]
Yesterday's error is unrelated to the JioTV Go update. It was from jio's end.If you're still experiencing issues, please clear the app data and try again.
