### ISSUE TITLE
[Bug]:  one plus tv

### ISSUE THREAD

**Issue by Kartikoo8** [siddharthsky/CustTermux-JioTVGo#60]
### Problem description

One plus tv in otp not send problem please fix and help me🙏

### What steps will reproduce the bug?

Help

### What is the expected behavior?

Otp receive

### System information

```shell
One plus tv
```

**Comment by siddharthsky** [comment]
Go to WEBTV and login from there

**Comment by pdahiya82** [comment]
But is show error while login by webtv

**Comment by siddharthsky** [comment]
> But is show error while login by webtv

Change port number, then login
