### ISSUE TITLE
[Bug]: Server didnot become live

### ISSUE THREAD

**Issue by Justaguynew** [siddharthsky/CustTermux-JioTVGo#61]
### Problem description

Installed v4.5 in OnePlus q2 pro tv server error showing server didnot become live after 5 attempts. I tried reinstalling from extras menu also reinstalled the apk. It still persists****
![IMG_20240925_180404](https://github.com/user-attachments/assets/879790f0-4963-4832-a10c-b6ed7a853978)
I tried it in two android smartphones. No problem. Working fine in Xiaomi mi 11x and Samsung S21 FE. Though in Mi 11x, initially I had no problem but on opening second time same problem found but after reinstalling it started working fine. 

### What steps will reproduce the bug?

Installing v4.5

### What is the expected behavior?

Server error. Showing server did not become live after 5 attempts

### System information

```shell
Server did not become live after 5 attempts
```

**Comment by siddharthsky** [comment]
On a OnePlus TV, you need to change the port from 5001 to something else, such as 5002 or any other number.

**Comment by Justaguynew** [comment]
Working after changing port. Thank you
