### ISSUE TITLE
Stucks

### ISSUE THREAD

**Issue by dhruv-glidetech** [siddharthsky/CustTermux-JioTVGo#8]
![IMG_20240731_203137_209](https://github.com/user-attachments/assets/e54aa368-46c3-447d-9112-05d5fe7fb672)
![IMG_20240731_195446](https://github.com/user-attachments/assets/0706f9e1-4d1c-4d52-9fec-983df485b970)

Tuscks even afer clear data....restarted it.... storages permission also given

**Comment by siddharthsky** [comment]
This issue is due to a problem with Termux-api. In the latest update, version 4.0, this has been addressed and resolved. Please update to [CustTermux 4.0](https://github.com/siddharthsky/CustTermux-JioTVGo/releases/tag/x0.123.4)
